### PR TITLE
Make setsockopt argument bytes

### PR DESCRIPTION
**Pull request by cielavenir**
background: we allow installing mujinplanningclientpy to both Python2 and Python3..

setsockopt_string accepts unicode on Py2 while it accepts str on Py3.
setsockopt accepts str on Py2 while it accepts bytes on Py3.

so one of these are compatible:

- socket.setsockopt(zmq.SUBSCRIBE, b'')
- socket.setsockopt_string(zmq.SUBSCRIBE, u'')

maybe the first one is better as it does not change any code path on py2.

### CODE REVIEW

**Comment by cielavenir** [comment]
fixed typos in desc

**Comment by felixvd** [comment]
The [tests pass](https://autotester.test.mujin.co.jp/?scheduleid=2&pipelineid=340565) and I don't see a reason not to do this. I just recently tripped up with strings and bytes though, so I'd want a second set of eyes. @lazydroid ?

**Comment by cielavenir** [comment]
@lazydroid

**Review by lazydroid — APPROVED** [review]
LGTM, thanks!

**Comment by cielavenir** [comment]
@felixvd

**Comment by felixvd** [comment]
Thanks!

**Pull request merged**
