### PR TITLE
Pass controller url, username, and password in userinfo

### PR DESCRIPTION
**Pull request by woswos**

### CODE REVIEW

**Comment by felixvd** [comment]
Why jump two version numbers?

**Comment by woswos** [comment]
@felixvd `Add master functions TerminateSlaves, CancelSlaves, Quit` _unrelased_ change was merged to master without bumping the version

**Comment by felixvd** [comment]
That change has been "Unreleased" since `0.1.6`. Somehow multiple devs just left it there.

Please move the line to `0.2.0` since it seems to have been there since that version, and make this bump one number.

**Review by rdiankov — APPROVED** [review]

**Comment by rdiankov** [comment]
thanks~

**Pull request merged**
